apiVersion: v1
kind: Service
metadata:
  name: jesus-osorio-service
spec:
  # Tipo NodePort para acceso local
  type: NodePort
  selector:
    # Debe coincidir con el label del Deployment
    app: jesus-microservice
  ports:
    - protocol: TCP
      port: 80           # Puerto del servicio (interno)
      targetPort: 80     # Puerto del contenedor (donde escucha uvicorn)
      nodePort: 30001    # Puerto fijo para acceder desde nuestra PC 